# .github/workflows/frontend.yml
name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
      
      - name: Deploy Frontend
        if: steps.changes.outputs.frontend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/aparthouse-umbrella
            git fetch --all
            git checkout master
            git pull origin master
            
            echo "Rebuilding frontend service..."
            docker compose up -d --build --no-deps frontend
            
            echo "Checking service status..."
            docker compose ps frontend